spring:
  kafka:
    consumer:
      group-id: plc-consumer-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  bootstrap-servers: localhost:9091,localhost:9094,localhost:9097
  consumer:
    topics:
      - plc_power_prod
      - plc_power_dev
      - plc_power_control
  producer:
    topics:
      plc_power_prod: resolved_power_prod
      plc_power_dev: resolved_power_dev
      plc_power_control: resolved_power_control
  consume:
    strategy: interval  # unlimited 或 interval
    interval-ms: 2000   # 拉取間隔（毫秒），interval 模式才用
